"""initial_schema_v1

Revision ID: 3c2c07e33ffd
Revises: 
Create Date: 2026-04-29 15:52:09.080405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3c2c07e33ffd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_provider',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider_type', sa.Text(), nullable=False),
    sa.Column('admin_phone_enc', sa.Text(), nullable=False),
    sa.Column('monthly_minute_quota', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('credit_code', sa.Text(), nullable=True),
    sa.Column('admin_phone_enc', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_minute_quota', sa.Integer(), nullable=True),
    sa.Column('minute_quota_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_code')
    )
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_enc')
    )
    op.create_table('owner_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=False),
    sa.Column('data_hash', sa.Text(), nullable=True),
    sa.Column('building', sa.Text(), nullable=True),
    sa.Column('room', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('do_not_call', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_ops_assignment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ops_user_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ops_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('property_pm_user_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_pm_user_id', sa.BigInteger(), nullable=True),
    sa.Column('plan_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_pm_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['service_provider.id'], ),
    sa.ForeignKeyConstraint(['provider_pm_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_tenant_contract',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_types', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_provider.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_minute_usage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('year_month', sa.Text(), nullable=False),
    sa.Column('used_minutes', sa.Integer(), nullable=False),
    sa.Column('quota_at_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year_month')
    )
    op.create_table('user_tenant_membership',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_hours', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['service_provider.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_case',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('pool_type', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('months_overdue', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_contact_count', sa.Integer(), nullable=False),
    sa.Column('data_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner_profile.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_tenant_assigned', 'collection_case', ['tenant_id', 'assigned_to'], unique=False)
    op.create_index('idx_case_tenant_pool', 'collection_case', ['tenant_id', 'pool_type'], unique=False)
    op.create_table('settlement_statement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','PAID','DISPUTED')", name='ck_settlement_status'),
    sa.ForeignKeyConstraint(['contract_id'], ['provider_tenant_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('caller_user_id', sa.BigInteger(), nullable=False),
    sa.Column('callee_phone_enc', sa.Text(), nullable=False),
    sa.Column('initiated_by', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('billable_duration', sa.Integer(), nullable=True),
    sa.Column('result_tag', sa.Text(), nullable=True),
    sa.Column('emotion_tag', sa.Text(), nullable=True),
    sa.Column('risk_flagged', sa.Boolean(), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('data_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caller_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['collection_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_callrecord_case', 'call_record', ['case_id'], unique=False)
    op.create_index('idx_callrecord_tenant', 'call_record', ['tenant_id'], unique=False)
    op.create_table('dispute_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['settlement_statement.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_case',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('amount_disputed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lawyer_name', sa.Text(), nullable=True),
    sa.Column('law_firm', sa.Text(), nullable=True),
    sa.Column('next_milestone', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['collection_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_segments', sa.JSON(), nullable=True),
    sa.Column('followup_suggestion', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=True),
    sa.Column('audio_offset_ms', sa.Integer(), nullable=True),
    sa.Column('intervention', sa.Text(), nullable=False),
    sa.Column('data_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_order',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=True),
    sa.Column('call_id', sa.BigInteger(), nullable=True),
    sa.Column('order_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['call_record.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['collection_case.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # transcript table: legacy rows exist → add call_id as nullable for now.
    # Sprint 1 will backfill and add NOT NULL after migrating legacy call_log data.
    op.add_column('transcript', sa.Column('call_id', sa.BigInteger(), nullable=True))
    op.add_column('transcript', sa.Column('data_hash', sa.Text(), nullable=True))
    op.add_column('transcript', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('asr_raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transcript', sa.Column('call_log_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcript', type_='foreignkey')
    op.create_foreign_key(op.f('transcript_call_log_id_fkey'), 'transcript', 'call_log', ['call_log_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transcript', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcript', 'segments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('transcript', 'updated_at')
    op.drop_column('transcript', 'data_hash')
    op.drop_column('transcript', 'call_id')
    op.drop_table('work_order')
    op.drop_table('risk_event')
    op.drop_table('analysis_result')
    op.drop_table('legal_case')
    op.drop_table('dispute_record')
    op.drop_index('idx_callrecord_tenant', table_name='call_record')
    op.drop_index('idx_callrecord_case', table_name='call_record')
    op.drop_table('call_record')
    op.drop_table('settlement_statement')
    op.drop_index('idx_case_tenant_pool', table_name='collection_case')
    op.drop_index('idx_case_tenant_assigned', table_name='collection_case')
    op.drop_table('collection_case')
    op.drop_table('user_tenant_membership')
    op.drop_table('tenant_minute_usage')
    op.drop_table('provider_tenant_contract')
    op.drop_table('project')
    op.drop_table('platform_ops_assignment')
    op.drop_table('owner_profile')
    op.drop_table('user_account')
    op.drop_table('tenant')
    op.drop_table('service_provider')
    # ### end Alembic commands ###
